# Generated by Django 3.2.4 on 2022-04-27 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_orders_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='user_id',
            new_name='user',
        ),
    ]
