# Generated by Django 3.2.4 on 2022-04-29 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_rename_user_id_orders_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='addmoney',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
