# Generated by Django 3.2.13 on 2022-04-30 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_auto_20220430_0326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='wallet_amount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
